name: 'CI'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: CMake generate build for SMF library
        run: |
          cmake -G Ninja -S . -B build-debug -DCMAKE_BUILD_TYPE=Debug
          cmake -G Ninja -S . -B build-release -DCMAKE_BUILD_TYPE=Release
      - name: CMake build SMF library
        run: |
          cmake --build build-debug
          cmake --build build-release

  build_ancestor:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: CMake generate build for SMF library with hierarchical state machine feature
        run: |
          cmake -G Ninja -S . -B build-debug -DCMAKE_BUILD_TYPE=Debug -DSMF_ANCESTOR_SUPPORT=ON
          cmake -G Ninja -S . -B build-release -DCMAKE_BUILD_TYPE=Release -DSMF_ANCESTOR_SUPPORT=ON
      - name: CMake build SMF library with hierarchical state machine feature
        run: |
          cmake --build build-debug
          cmake --build build-release

  build_clang:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        clang: [ '13.0', '14.0' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install LLVM and Clang - ${{ matrix.clang }}
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.clang }}
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: CMake generate build for SMF library with hierarchical state machine feature
        run: |
          cmake -G Ninja -S . -B build-debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
          cmake -G Ninja -S . -B build-release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
      - name: CMake build SMF library with hierarchical state machine feature
        run: |
          cmake --build build-debug
          cmake --build build-release

  build_clang_ancestor:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        clang: [ '13.0', '14.0' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install LLVM and Clang - ${{ matrix.clang }}
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.clang }}
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: CMake generate build for SMF library with hierarchical state machine feature
        run: |
          cmake -G Ninja -S . -B build-debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DSMF_ANCESTOR_SUPPORT=ON
          cmake -G Ninja -S . -B build-release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DSMF_ANCESTOR_SUPPORT=ON
      - name: CMake build SMF library with hierarchical state machine feature
        run: |
          cmake --build build-debug
          cmake --build build-release

  build_msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: CMake generate build for SMF library
        run: |
          cmake -G "Visual Studio 17 2022" -S . -B build-debug -DCMAKE_BUILD_TYPE=Debug
          cmake -G "Visual Studio 17 2022" -S . -B build-release -DCMAKE_BUILD_TYPE=Release
      - name: CMake build SMF library
        run: |
          cmake --build build-debug
          cmake --build build-release

  build_msvc_ancestor:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: CMake generate build for SMF library with hierarchical state machine feature
        run: |
          cmake -G "Visual Studio 17 2022" -S . -B build-debug -DCMAKE_BUILD_TYPE=Debug -DSMF_ANCESTOR_SUPPORT=ON
          cmake -G "Visual Studio 17 2022" -S . -B build-release -DCMAKE_BUILD_TYPE=Release -DSMF_ANCESTOR_SUPPORT=ON
      - name: CMake build SMF library with hierarchical state machine feature
        run: |
          cmake --build build-debug
          cmake --build build-release