name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Get latest CMake and Ninja
          uses: lukka/get-cmake@latest
        - name: CMake generate build for SMF library
          run: cmake -G Ninja -S . -B build
        - name: CMake build SMF library
          run: cmake --build build
        - name: CMake generate build for SMF library with hierarchical state machine feature
          run: cmake -G Ninja -S . -B build -DSMF_ANCESTOR_SUPPORT=ON
        - name: CMake build SMF library with hierarchical state machine feature
          run: cmake  --build build
